export const UIBUILDER_INIT 			  			= 'UIBUILDER_INIT';
export const UIBUILDER_UPDATE_NODE_ATTRIBUTE      	= 'UIBUILDER_UPDATE_NODE_ATTRIBUTE';
export const UIBUILDER_UPDATE_NODE_STYLE          	= 'UIBUILDER_UPDATE_NODE_STYLE';
export const UIBUILDER_UPDATE_NODE_TRANSFORM      	= 'UIBUILDER_UPDATE_NODE_TRANSFORM';
export const UIBUILDER_CLONE_NODE		  			= 'UIBUILDER_CLONE_NODE';
export const UIBUILDER_CLONE_NODE_WITH_STYLE		= 'UIBUILDER_CLONE_NODE_WITH_STYLE';
export const UIBUILDER_CLONE_NODE_WITH_ATTRIBUTE   = 'UIBUILDER_CLONE_NODE_WITH_ATTRIBUTE';
export const UIBUILDER_CLONE_NODE_WITH_TRANSFORM   = 'UIBUILDER_CLONE_NODE_WITH_TRANSFORM';
export const UIBUILDER_REMOVE_NODE 		  			= 'UIBUILDER_REMOVE_NODE';
export const UIBUILDER_ADD_MAPPING		  			= 'UIBUILDER_ADD_MAPPING';
export const UIBUILDER_PROVENANCE 		  			= 'UIBUILDER_PROVENANCE';
export const UIBUILDER_PROVENANCE_SELECT_MAPPING 	= 'UIBUILDER_PROVENANCE_SELECT_MAPPING';
export const UIBUILDER_RECORD_PATH		  			= 'UIBUILDER_RECORD_PATH';
export const UIBUILDER_INCREMENT_TICK				= 'UIBUILDER_INCREMENT_TICK';

export const APP_INIT = 'APP_INIT';
export const APP_MESSAGE = 'APP_MESSAGE';
export const APP_REMOVED = 'APP_REMOVED';
export const APP_RESET = 'APP_RESET';

export const NETWORK_ACCESS = 'NETWORK_ACCESS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_SUCCESS = 'NETWORK_SUCCESS';
export const NETWORK_COMPLETE = 'NETWORK_COMPLETE';

export const WINDOW_RESIZED = 'WINDOW_RESIZED';